/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Leyla
 */
public class Lab4_3 extends javax.swing.JFrame {

    double[] book_prices = new double[]{ 3.5,2.8,10,7.4,6.9 }; 
    double[] books = new double[5];
    
    public Lab4_3() {
        initComponents();
        setSize(630,400);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBooks = new javax.swing.JPanel();
        lblBook1 = new javax.swing.JLabel();
        txtBook1 = new javax.swing.JTextField();
        lblBook2 = new javax.swing.JLabel();
        txtBook2 = new javax.swing.JTextField();
        lblBook3 = new javax.swing.JLabel();
        txtBook3 = new javax.swing.JTextField();
        lblBook4 = new javax.swing.JLabel();
        txtBook4 = new javax.swing.JTextField();
        lblBook5 = new javax.swing.JLabel();
        txtBook5 = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        txtInfo = new javax.swing.JLabel();
        lblBook = new javax.swing.JLabel();
        cmbBook = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBook = new javax.swing.JTextArea();
        btnTOTAL = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBooks.setBorder(javax.swing.BorderFactory.createTitledBorder("Book Quantities"));

        lblBook1.setText("Book1:");

        lblBook2.setText("Book2:");

        lblBook3.setText("Book3:");

        lblBook4.setText("Book4:");

        lblBook5.setText("Book5:");

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBooksLayout = new javax.swing.GroupLayout(pnlBooks);
        pnlBooks.setLayout(pnlBooksLayout);
        pnlBooksLayout.setHorizontalGroup(
            pnlBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBooksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlBooksLayout.createSequentialGroup()
                            .addComponent(lblBook1)
                            .addGap(18, 18, 18)
                            .addComponent(txtBook1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlBooksLayout.createSequentialGroup()
                            .addComponent(lblBook2)
                            .addGap(18, 18, 18)
                            .addComponent(txtBook2))
                        .addGroup(pnlBooksLayout.createSequentialGroup()
                            .addComponent(lblBook3)
                            .addGap(18, 18, 18)
                            .addComponent(txtBook3))
                        .addGroup(pnlBooksLayout.createSequentialGroup()
                            .addComponent(lblBook4)
                            .addGap(18, 18, 18)
                            .addComponent(txtBook4))
                        .addGroup(pnlBooksLayout.createSequentialGroup()
                            .addComponent(lblBook5)
                            .addGap(18, 18, 18)
                            .addGroup(pnlBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtBook5)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBooksLayout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(btnAdd)
                                    .addGap(60, 60, 60)))))
                    .addComponent(txtInfo))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pnlBooksLayout.setVerticalGroup(
            pnlBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBooksLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBook1)
                    .addComponent(txtBook1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBook2)
                    .addComponent(txtBook2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBook3)
                    .addComponent(txtBook3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBook4)
                    .addComponent(txtBook4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBook5)
                    .addComponent(txtBook5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAdd)
                .addGap(18, 18, 18)
                .addComponent(txtInfo)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 350));

        lblBook.setText("Select Book:");
        getContentPane().add(lblBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        cmbBook.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        getContentPane().add(cmbBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 60, 20));

        txtBook.setColumns(20);
        txtBook.setRows(5);
        jScrollPane1.setViewportView(txtBook);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 290, 190));

        btnTOTAL.setText("TOTAL");
        btnTOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTOTALActionPerformed(evt);
            }
        });
        getContentPane().add(btnTOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        btnShow.setText("SHOW");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });
        getContentPane().add(btnShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       int book1 = Integer.parseInt(txtBook1.getText());
       int book2 = Integer.parseInt(txtBook2.getText());
       int book3 = Integer.parseInt(txtBook3.getText());
       int book4 = Integer.parseInt(txtBook4.getText());
       int book5 = Integer.parseInt(txtBook5.getText());
       
       books[0] = book_prices[0]*book1;
       books[1] = book_prices[1]*book2;
       books[2] = book_prices[2]*book3;
       books[3] = book_prices[3]*book4;
       books[4] = book_prices[4]*book5;
        
       txtInfo.setText("Book Quantities are added");
       
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        int selected = cmbBook.getSelectedIndex();
        if(selected == 0)
            txtBook.setText("BOOK1 PRICE IS "+books[0]);
        else if(selected == 1)
            txtBook.setText("BOOK2 PRICE IS "+books[1]);
        else if(selected == 2)
             txtBook.setText("BOOK3 PRICE IS "+books[2]);
        else if(selected == 3)
            txtBook.setText("BOOK4 PRICE IS "+books[3]);
        else if(selected == 4)
             txtBook.setText("BOOK5 PRICE IS "+books[4]);
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnTOTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTOTALActionPerformed
        
        double total = 0.0;
        for (int i = 0; i < 5; i++) {
            total += books[i];
        }
        txtBook.setText("TOTAL Price for all books "+total);
    }//GEN-LAST:event_btnTOTALActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab4_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab4_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab4_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab4_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab4_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnTOTAL;
    private javax.swing.JComboBox cmbBook;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBook;
    private javax.swing.JLabel lblBook1;
    private javax.swing.JLabel lblBook2;
    private javax.swing.JLabel lblBook3;
    private javax.swing.JLabel lblBook4;
    private javax.swing.JLabel lblBook5;
    private javax.swing.JPanel pnlBooks;
    private javax.swing.JTextArea txtBook;
    private javax.swing.JTextField txtBook1;
    private javax.swing.JTextField txtBook2;
    private javax.swing.JTextField txtBook3;
    private javax.swing.JTextField txtBook4;
    private javax.swing.JTextField txtBook5;
    private javax.swing.JLabel txtInfo;
    // End of variables declaration//GEN-END:variables
}
